### ISSUE TITLE
Track Hands/Wrists only?

### ISSUE THREAD

**Issue by JoshuaHeim** [CMU-Perceptual-Computing-Lab/openpose_unity_plugin#18]
### Issue Summary
I would like to track hands only or even just the wrist joint. Is there a way to do this that I am missing?

### Type of Issue
You might select multiple topics, delete the rest:

- Help wanted
- Question

I am working on a gesture control system and would like to know if there is a way to isolate the hands and/or wrist joints and only use those. I don't need the legs, torso, or face and just disabling the visuals for them seems to be a cheap way of doing it. Where in what code should I be looking to track only certain joints?

Thanks

**Comment by gineshidalgo99** [comment]
OpenPose does detect everything at once, e.g. where the shoulder is implicitly helps locate the wrist. So if you only wanna use wrist joints, then yes, disabling the visual output is actually the best way to do it, because they still help locating the hand (at least indirectly). Re-training OpenPose to only work with wrist should not be as accurate.
